motd:
  # 支持 & 颜色码
  # 支持占位符：{version} {mspt} {joinsToday}
  line1: "§4§l风之羽 §8§l休闲｜养老｜原版生存"
  line2: "&e版本 &f{version}&7|&aMSPT&f{mspt}ms&7|&b本日登录人次&f{joinsToday}"

  # MSPT 显示保留小数位
  mspt-decimals: 1